baseurl: ""

collections:
  projects:
    output: true
  categories:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  # categories:

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
